/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2014 University of Manchester
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package uk.ac.manchester.cs.mekon.owl.util;

import java.util.*;

import org.semanticweb.owlapi.model.*;

import uk.ac.manchester.cs.mekon.model.*;
import uk.ac.manchester.cs.mekon.store.motor.*;

/**
 * Manages the assignment of unique IRIs to a set of OWL-based
 * representaions of static MEKON frames-model instantiations.
 *
 * @author Colin Puleston
 */
public class OStaticInstanceIRIs extends OInstanceIRIs {

	static private final String NAMESPACE_EXTN = "";

	private IMatcherIndexes indexes = new LocalIndexes();

	/**
	 * Resets the index manager used in generating the IRIs. By default
	 * a locally created manager will be used.
	 *
	 * @return Index manager to be used
	 */
	public void resetIndexes(IMatcherIndexes indexes) {

		this.indexes = indexes;
	}

	/**
	 * Provides the unique IRI that will be used to represent the
	 * specified instance. This will either be derived directly from
	 * instance identifier, if that identifier has an appropriate
	 * format, or else generated from the unique index value that has
	 * been assigned to the instance.
	 *
	 * @param identity Identity of instance for which IRI is required
	 * @return Relevant IRI
	 */
	public IRI get(CIdentity identity) {

		int index = indexes.getIndex(identity);
		IRI iri = O_IRIExtractor.extractIRI(identity);

		return iri != null ? iri : create(index);
	}

	/**
	 * Tests whether an IRI has been derived directly from an instance
	 * identifier of an appropriate format, or else has the format that
	 * would be generated by this class.
	 *
	 * @param iri IRI to test
	 * @return true if IRI has relevant format
	 */
	public boolean staticInstance(IRI iri) {

		return generatedIRI(iri, NAMESPACE_EXTN) || predefinedIRI(iri);
	}

	/**
	 * {@inheritDoc}
	 */
	public CIdentity toIdentity(IRI iri) {

		return predefinedIRI(iri) ? asIdentity(iri) : super.toIdentity(iri);
	}

	String getNamespaceExtn() {

		return NAMESPACE_EXTN;
	}

	CIdentity toIdentity(int index) {

		return indexes.getIdentity(index);
	}

	private boolean predefinedIRI(IRI iri) {

		return indexes.hasIndex(asIdentity(iri));
	}

	private CIdentity asIdentity(IRI iri) {

		return new CIdentity(iri.toString());
	}
}
