/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2014 University of Manchester
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package uk.ac.manchester.cs.mekon.model.serial;

import java.util.*;

import uk.ac.manchester.cs.mekon.model.*;
import uk.ac.manchester.cs.mekon.model.util.*;

/**
 * Represents the input-data for a specific {@link IFrame}/{@link ISlot}
 * network rendering operation to be performed by a {@link IInstanceRenderer},
 * including structures into which certain output-data may be written.
 *
 * @author Colin Puleston
 */
public class IInstanceRenderInput {

	private IFrame rootFrame;
	private IValuesUpdate valuesUpdate = IValuesUpdate.NO_UPDATE;

	private Map<IFrame, String> frameXDocIds = new HashMap<IFrame, String>();

	/**
	 * Constructor.
	 *
	 * @param rootFrame Root-frame of network to be rendered
	 */
	public IInstanceRenderInput(IFrame rootFrame) {

		this.rootFrame = rootFrame;
	}

	/**
	 * Registers the latest client-update operation prior to the network
	 * being rendered.
	 * <p>
	 * NOTE: This information, if applicable, should be provided when sending
	 * information to the server for automatic-update.
	 *
	 * @param valuesUpdate Latest client-update operation
	 */
	public void setValuesUpdate(IValuesUpdate valuesUpdate) {

		this.valuesUpdate = valuesUpdate;
	}

	/**
	 * Sets the map of document-specific frame-identifiers to be used by
	 * the renderer, possibly fully or partially pre-populated. Identifiers
	 * will be generated and written into the map for any frames that are
	 * not represented in the initial version.
	 *
	 * @param frameXDocIds Map of frames to document-specific frame-identifiers,
	 * either fully or partially populated
	 */
	public void setFrameXDocIds(Map<IFrame, String> frameXDocIds) {

		this.frameXDocIds = frameXDocIds;
	}

	/**
	 * Provides the map that will contain the document-specific
	 * frame-identifiers used by the renderer. The identifiers can be
	 * either pre-provided via the {@link setFrameXDocIds} method,
	 * automatically generated by the renderer, or a mixture of both.
	 *
	 * @return Map of frames to document-specific frame-identifiers
	 */
	public Map<IFrame, String> getFrameXDocIds() {

		return frameXDocIds;
	}

	IFrame getRootFrame() {

		return rootFrame;
	}

	boolean includesValuesUpdate() {

		return valuesUpdate != null;
	}

	IValuesUpdate getValuesUpdate() {

		if (valuesUpdate == null) {

			throw new Error("Values-update has not been set!");
		}

		return valuesUpdate;
	}
}
